NoiThat/Areas/admin/Controllers/OrderController.cs
using NoiThat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Mail;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using NoiThat.Controllers;

namespace NoiThat.Areas.admin.Controllers
{
    public class OrderController : Controller
    {
        public dbNoiThatOnlineDataContext data;

        public OrderController()
        {
            data = Connect.GetConnect();
        }
        public ActionResult Index(int ? page)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            int iSize = 6;
            int iPage = page ?? 1;
            var lst = data.orders.Where(od => od.status == 0).ToList();
            return View(lst.ToPagedList(iPage, iSize));
        }

        public ActionResult daDuyet(int ? page)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            int iSize = 6;
            int iPage = page ?? 1;
            var lst = data.orders.Where(od => od.status == 1).ToList();
            return View(lst.ToPagedList(iPage,iSize));
        }

        public ActionResult deleteView(int id)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var od = data.orders.SingleOrDefault(n=>n.id== id);
            return View(od);
        }

        public ActionResult delete(int id,FormCollection f) 
        {
            var od = data.orders.SingleOrDefault(n => n.id == id);
            var kh = data.customers.SingleOrDefault(n => n.id == od.customer_id);
            var listOrderDetails = data.orderDetails.Where(od1 => od1.order_id == id).ToList();
            var liDo = f["lyDo"];
            data.orders.DeleteOnSubmit(od);
            data.SubmitChanges();
            var fromEmail = "Nội Thất Sky<tiktokofme10022003@gmail.com>";
            var subject = "Hủy đơn hàng";

            var body = "Đơn hàng #DH" + od.id + " đã bị hủy\n";
            body += "\nLý do hủy đơn : " + liDo + "\n";
            body += "<table style='border-collapse: collapse; width: 100%; border: 1px solid #ddd;'>" +
              "<tr><th style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Sản phẩm</th>" +
              "<th style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Số lượng</th>" +
              "<th style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Giá</th></tr>";
            foreach (var orderDetail in listOrderDetails)
            {
                var product = data.products.SingleOrDefault(p => p.id == orderDetail.product_id);
                if (product != null)
                {
                    body += $"<tr><td style='border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: normal;'>{product.name}</td>" +
                            $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: normal;'>{orderDetail.quantity}</td>" +
                            $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: normal;'>{orderDetail.price:#,##} VND</td></tr>";
                }
            }
            body += $"<tr><td colspan='2' style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Tổng hóa đơn:</td>" +
                   $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center;'>{od.totalPrice:#,##} VND</td></tr>";
            body += "</table>";

            using (var mail = new MailMessage(fromEmail, kh.email))
            {
                mail.Subject = subject;
                mail.Body = body;

                mail.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.Credentials = new System.Net.NetworkCredential("tiktokofme10022003@gmail.com", "msmdawujowxaddqd");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

NoiThat/Areas/admin/Controllers/OrderDetailController.cs
using NoiThat.Controllers;
using NoiThat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NoiThat.Areas.admin.Controllers
{
    public class OrderDetailController : Controller
    {
        public dbNoiThatOnlineDataContext data;

        public OrderDetailController()
        {
            data = Connect.GetConnect();
        }
        public ActionResult Index(int id)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var lst = data.orderDetails.FirstOrDefault(n => n.order_id == id);
            return View(lst);
        }

        public ActionResult daDuyet(int id)
        {
            var lst = data.orderDetails.FirstOrDefault(n => n.order_id == id);
            return View(lst);
        }

        public ActionResult customersPartial(int id) 
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var lst = data.customers.SingleOrDefault(n => n.id == id);
            return PartialView(lst);
        }

        public ActionResult ProductPartial(int id)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var listOrderDetails = data.orderDetails.Where(od => od.order_id == id).ToList();
            return PartialView(listOrderDetails);
        }

        public ActionResult XacNhanDon(int id, FormCollection f)
        {
            DateTime ngayGiaoDate = DateTime.Parse(f["ngayGiao"]);
            var od = data.orders.SingleOrDefault(n => n.id == id);
            var listOrderDetails = data.orderDetails.Where(od1 => od1.order_id == id).ToList();
            var kh  = data.customers.SingleOrDefault(n=>n.id == od.customer_id);
            od.date_delivery = ngayGiaoDate;
            od.status = 1;
            od.paymentStatus = 1;
            data.SubmitChanges();
            var fromEmail = "Nội Thất Sky<tiktokofme10022003@gmail.com>";
            var subject = "Đơn hàng";
            string body = "<h2>Đơn Hàng #ĐH" + od.id + " đã giao hàng</2></br>";
            body += "<table style='border-collapse: collapse; width: 100%; border: 1px solid #ddd;'>" +
               "<tr><th style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Sản phẩm</th>" +
               "<th style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Số lượng</th>" +
               "<th style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Giá</th></tr>";

            foreach (var orderDetail in listOrderDetails)
            {
                var product = data.products.SingleOrDefault(p => p.id == orderDetail.product_id);
                if (product != null)
                {
                    body += $"<tr><td style='border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: normal;'>{product.name}</td>" +
                            $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: normal;'>{orderDetail.quantity}</td>" +
                            $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: normal;'>{orderDetail.price:#,##} VND</td></tr>";
                }
            }

            body += $"<tr><td colspan='2' style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Tổng hóa đơn:</td>" +
                    $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center;'>{od.totalPrice:#,##} VND</td></tr>";
            body += $"<tr><td colspan='2' style='border: 1px solid #ddd; padding: 8px; text-align: center;'>Ngày giao hàng:</td>" +
                   $"<td style='border: 1px solid #ddd; padding: 8px; text-align: center;'>{ngayGiaoDate.Date.ToString("dd/MM/yyyy")}</td></tr>";
            body += "</table>";
            // Rest of your email sending code
            using (var mail = new MailMessage(fromEmail, kh.email))
            {
                mail.Subject = subject;
                mail.Body = body;

                mail.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.Credentials = new System.Net.NetworkCredential("tiktokofme10022003@gmail.com", "msmdawujowxaddqd");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }
            return RedirectToAction("Index", "Order");


        }
    }
}

NoiThat/Areas/admin/Views/Order/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

@using NoiThat;
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<NoiThat.Models.order>

<style>
    .pagination-container {
        text-align: center;
        margin-top: 20px;
    }

    .pagination {
        display: inline-block;
    }

        .pagination li {
            display: inline;
            margin: 0 5px;
        }

        .pagination a {
            color: #333;
            text-decoration: none;
            padding: 8px 16px;
            border: 2px solid #333;
            border-radius: 4px;
        }

            .pagination a:hover, .pagination .active {
                background-color: #333;
                color: #fff;
            }
</style>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Đơn hàng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Đơn hàng</a></li>
                    <li class="breadcrumb-item active">Blank Page</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã đơn hàng</th>
                        <th>Email</th>
                        <th>Ngày tạo đơn</th>
                        <th>Tổng hóa đơn</th>
                        <th>Thanh Toán</th>
                        <th>Phương thức</th>
                        <th>Tùy chỉnh</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var count = Model.PageNumber * Model.PageSize - Model.PageSize + 1;
                        foreach (var order in Model)
                        {
                            <tr>
                                <td>@count</td>
                                <td>#DH@(order.id)</td>
                                <td>@order.customer.email</td>
                                <td>@order.date_create</td>
                                <td>@Html.FormatValue(order.totalPrice, "{0:#,##0}")</td>
                                <td>@(order.paymentStatus == 0 ? "Chưa thanh toán":"Đã thanh toán")</td>
                                <td>@order.paymentMethod</td>
                                <td>
                                    <a href="@Url.Action("Index", "OrderDetail", new { id = order.id })" class="btn btn-sm btn-success">Giao hàng</a>
                                    <a href="@Url.Action("deleteView", "Order", new { id = order.id })" class="btn btn-sm btn-danger">Hủy đơn</a>
                                </td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="7">Không có bản ghi!!!</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="text-center pagination-container">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
</section>

NoiThat/Areas/admin/Views/Order/daDuyet.cshtml
@{
    ViewBag.Title = "daDuyet";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}
@using NoiThat;
@using PagedList.Mvc;
@model PagedList.PagedList<NoiThat.Models.order>
<style>
    .pagination-container {
        text-align: center;
        margin-top: 20px; /* Add margin for spacing */
    }

    .pagination {
        display: inline-block;
    }

        .pagination li {
            display: inline;
            margin: 0 5px;
        }

        .pagination a {
            color: #333;
            text-decoration: none;
            padding: 8px 16px;
            border: 2px solid #333;
            border-radius: 4px;
        }

            .pagination a:hover, .pagination .active {
                height: 40px;
                width: 40px;
                background-color: #333;
                color: #fff;
                border: 2px solid #333;
            }
</style>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Đơn hàng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Đơn hàng</a></li>
                    <li class="breadcrumb-item active">Blank Page</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã đơn hàng</th>
                        <th>Email</th>
                        <th>Ngày tạo đơn</th>
                        <th>Tổng hóa đơn</th>
                        <th>Thanh Toán</th>
                        <th>Phương thức</th>
                        <th>Tùy chỉnh</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var count = 1;
                        foreach (var i in Model)
                        {
                            <tr>
                                <td>@count</td>
                                <td>#DH@(i.id)</td>
                                <td>@i.customer.email</td>
                                <td>@i.date_create</td>
                                <td>@Html.FormatValue(@i.totalPrice, "{0:#,##0}")</td>
                                <td>@(i.paymentStatus == 0 ? "Chưa thanh toán":"Đã thanh toán")</td>
                                <td>@i.paymentMethod</td>
                                <td>
                                    <a href="@Url.Action("daDuyet","OrderDetail", new {id = @i.id})" class="btn btn-sm btn-primary">Xem</a>
                                </td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi!!!</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="text-center pagination-container">
        @Html.PagedListPager(Model , page => Url.Action("daDuyet" , new {page = page}))
    </div>
</section>

NoiThat/Areas/admin/Views/Order/deleteView.cshtml
@{
    ViewBag.Title = "deleteView";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}
@using (Html.BeginForm("delete", "Order", new { id =  @Model.id })) {
<div class="container">
    <div class="card">
        <div class="card-body">
            <form>
                <div class="form-group">
                    <label for="mota">Lý do :</label>
                    <textarea class="form-control" rows="3" id="mota" name="lyDo"></textarea>
                </div>
            </form>
            <div class="card-footer">
            <button type="submit" class="btn btn-danger">Hủy đơn</button>
            </div>
        </div>
    </div>
</div>
}