NoiThat/Areas/admin/Controllers/SloganController.cs
using NoiThat.Controllers;
using NoiThat.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoiThat.Areas.admin.Controllers
{
    public class SloganController : Controller
    {
        public dbNoiThatOnlineDataContext data;

        public SloganController()
        {
            data = Connect.GetConnect();
        }
        public ActionResult Index(int ? page)
        {
            int size = 6;
            int Page = page ?? 1;
            var lst = from cd in data.Slogans select cd;
            if (Session["admin"] != null)
            {
                return View(lst.ToPagedList(Page,size));
            }
            else
            {
                return RedirectToAction("Index", "loginAdmin");
            }
        }

        public ActionResult addSloganView()
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            return View();
        }

        public ActionResult updateSloganView(int id)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var sl = data.Slogans.SingleOrDefault(s => s.id == id);
            return View(sl);
        }

        public ActionResult addSlogan(FormCollection f)
        {
            var nd = f["slogan"];
            Slogan slogan = new Slogan();
            slogan.noi_dung = nd;
            data.Slogans.InsertOnSubmit(slogan);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult delete(int id)
        {
            var sl = data.Slogans.SingleOrDefault(n => n.id == id);
                data.Slogans.DeleteOnSubmit(sl);
                data.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult updateSlogan(int id,FormCollection f)
        {
            var sl = data.Slogans.SingleOrDefault(s => s.id == id);
            var nd = f["slogan"];
            if (nd != null)
            {
                sl.noi_dung = nd;
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

NoiThat/Areas/admin/Views/Slogan/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

@using NoiThat.Models
@using PagedList.Mvc
@model PagedList.PagedList<Slogan>
<style>
    .pagination-container {
        text-align: center;
        margin-top: 20px; /* Add margin for spacing */
    }

    .pagination {
        display: inline-block;
    }

        .pagination li {
            display: inline;
            margin: 0 5px;
        }

        .pagination a {
            color: #333;
            text-decoration: none;
            padding: 8px 16px;
            border: 2px solid #333;
            border-radius: 4px;
        }

            .pagination a:hover, .pagination .active {
                height: 40px;
                width: 40px;
                background-color: #333;
                color: #fff;
                border: 2px solid #333;
            }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Slogan</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh mục cấp 1</a></li>
                    <li class="breadcrumb-item active">Blank Page</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách</h3>

            <div class="card-tools">
                <a href="@Url.Action("addSloganView","Slogan")" class="btn btn-primary">Thêm mới</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>ID Sologan</th>
                        <th>Tùy chỉnh</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var count = 1;
                        foreach (var i in Model)
                        {
                            <tr>
                                <td>@count</td>
                                <td>@i.id</td>
                                <td>
                                    <a href="@Url.Action("updateSloganView","Slogan", new {id = @i.id})" class="btn btn-sm btn-warning">Sửa</a>
                                    <a href="@Url.Action("delete","Slogan", new {id = @i.id})" class="btn btn-sm btn-danger">Xóa</a>
                                </td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi!!!</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="text-center pagination-container">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
</section>

NoiThat/Areas/admin/Views/Slogan/addSloganView.cshtml
@{
    ViewBag.Title = "addSloganView";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}


@using (Html.BeginForm("addSlogan", "Slogan"))
{
    <div class="card">
        <div class="card-body">
            <div class="form-group">
                <label for="mota">Nội dung Slogan</label>
                <textarea class="form-control" rows="3" id="mota" name="slogan"></textarea>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
}

NoiThat/Areas/admin/Views/Slogan/updateSloganView.cshtml
@{
    ViewBag.Title = "updateSloganView";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

@using (Html.BeginForm("updateSlogan", "Slogan", new { @Model.id }))
{
    <div class="card">
        <div class="card-body">
            <div class="form-group">
                <label for="mota">Mô Tả</label>
                <textarea class="form-control" rows="3" id="mota" name="slogan">@Model.noi_dung</textarea>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
}