NoiThat/Controllers/NoiThatOnlineController.cs
using NoiThat.Models;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.IO.Ports;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoiThat.Controllers
{
    public class NoiThatOnlineController : Controller
    {
        // GET: NoiThatOnline
        public dbNoiThatOnlineDataContext data ;

        public NoiThatOnlineController()
        {
            data = Connect.GetConnect();
        }
        public ActionResult newProduct()
        {
            var listSpMoi = LaySpMoi(6);
            return PartialView(listSpMoi);
        }
        public ActionResult Index()
        {
            var listSpMoi = data.products.ToList();
            return View(listSpMoi);
        }
        public ActionResult danhMucPartial()
        {
            var listDanhMuc = from cd in data.categories select cd;
            return PartialView(listDanhMuc);
        }
        public ActionResult sloganPartial()
        {
            var list = from cd in data.Slogans select cd;
            return PartialView(list);
        }
        private List<product> LaySpMoi(int count)
        {
            return data.products.OrderByDescending(a => a.ngayCapNhap).Take(count).ToList();
        }
        public ActionResult SanPhamTheoDanhMuc(int id, int ? page)
        {
            ViewBag.MaSP = id;
            int iSize = 3;
            int iPageNum = (page ?? 1);
            var sp = from c in data.products where c.category_id == id select c;
            return View(sp.ToPagedList(iPageNum,iSize));
        }
        public ActionResult chiTietSanPham(int id)
        {
            var sp = data.products.FirstOrDefault(p => p.id == id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }
        public ActionResult timKienSanPham(FormCollection f)
        {
            var find = f["find"];
            var results = data.products.Where(p => p.name.Contains(find)).ToList();
            return View(results);
        }
    }
}

NoiThat/Views/NoiThatOnline/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


<!-- banner bg main end -->
<!-- fashion section start -->
<div class="fashion_section">
    <div id="main_slider" class="carousel slide" data-ride="carousel">
            @Html.Action("newProduct", "NoiThatOnline")
        <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div>
<!-- fashion section end -->
<!-- electronic section start -->
<div class="jewellery_section">
    <div id="jewellery_main_slider" class="carousel slide" data-ride="carousel">
        <div class="fashion_taital_container">
            <h1 class="fashion_taital">Bàn Ghế Sofa</h1>
        </div>

        <div class="fashion_section_2">
            <div class="container">
                <div class="row">
                    @foreach (var pr in Model)
                    {
                        if (pr.category.name == "Ghế Sofa")
                        {
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">@pr.name</h4>
                                    <p class="price_text">Price <span style="color: #262626;">@Html.FormatValue(pr.price, "{0:#,##0}") VNĐ</span></p>
                                    <div class="tshirt_img"><img src="~/images/@pr.image" alt="@pr.name"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a class="add-to-cart" href="#" data-ms="@pr.id">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="@Url.Action("chiTietSanPham","NoiThatOnline", new { id = pr.id})">See More</a></div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- electronic section end -->
<!-- jewellery  section start -->
<div class="jewellery_section">
    <div id="jewellery_main_slider" class="carousel slide" data-ride="carousel">
        <div class="fashion_taital_container">
            <h1 class="fashion_taital">Đèn Chùm Cao Cấp</h1>
        </div>

        <div class="fashion_section_2">
            <div class="container">
                <div class="row">
                    @foreach (var pr in Model)
                    {
                        if (pr.category.name == "Đèn chùm")
                        {
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main grayscale-effect">
                                    <h4 class="shirt_text">@pr.name</h4>
                                    <p class="price_text">Price <span style="color: #262626;">@Html.FormatValue(pr.price, "{0:#,##0}") VNĐ</span></p>
                                    <div class="tshirt_img"><img src="~/images/@pr.image" alt="@pr.name"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a class="add-to-cart" href="#" data-ms="@pr.id">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="@Url.Action("chiTietSanPham","NoiThatOnline", new { id = pr.id})">See More</a></div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<!-- footer section end -->
<!-- copyright section start -->
<div class="copyright_section">
    <div class="container">
        <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
    </div>
</div>
<!-- copyright section end -->
<!-- Javascript files-->
<script src="~/js/jquery.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/js/jquery-3.0.0.min.js"></script>
<script src="~/js/plugin.js"></script>
<!-- sidebar -->
<script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/js/custom.js"></script>
<script>
         function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
             }

         function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
         }
</script>

NoiThat/Views/NoiThatOnline/newProduct.cshtml
        <div class="carousel-inner">
            @for (var i = 0; i < Model.Count; i += 3)
            {
                <div class="carousel-item @if (i == 0) { <text>active</text> }">
                    <div class="container">
                        <h1 class="fashion_taital">Sản Phẩm Mới Nhất</h1>
                        <div class="fashion_section_2">
                            <div class="row">
                                @for (var j = i; j < i + 3 && j < Model.Count; j++)
                                {
                                    var pr = Model[j];
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="box_main">
                                            <h4 class="shirt_text">@pr.name</h4>
                                            <p class="price_text">Price <span style="color: #262626;">@Html.FormatValue(pr.price, "{0:#,##0}") VNĐ</span></p>
                                            <div class="tshirt_img"><img src="~/images/@pr.image"></div>
                                            <div class="btn_main">
                                                <div class="buy_bt"><a class="add-to-cart" href="#" data-ms="@pr.id">Buy Now</a></div>
                                                <div class="seemore_bt"><a href="@Url.Action("chiTietSanPham","NoiThatOnline", new { id = pr.id})">See More</a></div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

NoiThat/Views/NoiThatOnline/sloganPartial.cshtml
@model IEnumerable<NoiThat.Models.Slogan>

    <div class="container">
        <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                @foreach (var i in Model)
                {
                    <div class="carousel-item @(i == Model.First() ? "active" : "")">
                        <div class="row">
                            <div class="col-sm-12">
                                <h1 class="banner_taital sologan">@i.noi_dung</h1>
                                <div class="buynow_bt"><a href="#">Mua Ngay</a></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>

NoiThat/Views/NoiThatOnline/timKienSanPham.cshtml
@{
    ViewBag.Title = "timKienSanPham";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="jewellery_section">
    <div id="jewellery_main_slider" class="carousel slide" data-ride="carousel">
        <div class="fashion_taital_container">
            <h1 class="fashion_taital kq">Kết Quả Tìm Kiếm...</h1>
        </div>

        <div class="fashion_section_2">
            <div class="container">
                <div class="row">
                    @foreach (var pr in Model)
                    {
                        <div class="col-lg-4 col-sm-4">
                            <div class="box_main">
                                <h4 class="shirt_text">@pr.name</h4>
                                <p class="price_text">Price <span style="color: #262626;">@Html.FormatValue(pr.price, "{0:#,##0}") VNĐ</span></p>
                                <div class="tshirt_img"><img src="~/images/@pr.image"></div>
                                <div class="btn_main">
                                    <div class="buy_bt"><a href="@Url.Action("ThemGioHangttt","GioHang", new {ms = pr.id})">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="@Url.Action("chiTietSanPham","NoiThatOnline", new { id = pr.id})">See More</a></div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Các tệp script tiếp theo của bạn ở đây -->

<script src="~/js/jquery.min.js"></script>
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/js/jquery-3.0.0.min.js"></script>
<script src="~/js/plugin.js"></script>
<!-- sidebar -->
<script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/js/custom.js"></script>
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const targetElement = document.querySelector(".kq");

        if (targetElement) {
            const targetPosition = targetElement.getBoundingClientRect().top;
            const offset = 150;

            window.scrollBy({
                top: targetPosition - offset,
                behavior: "smooth"
            });
        }
    });
</script>